### ISSUE TITLE
Add 404 not found page

### ISSUE THREAD

**Issue by BaggioGiacomo** [ProjectWorkGruppo3/Frontend#45]
It will be nice to have a custom 404 not found page (e.g: we can put a little floating buddy that says "Ops, looks like you're lost!")

@saliougaye What do you think?

[Docs](https://nextjs.org/docs/advanced-features/custom-error-page)

**Comment by saliougaye** [comment]
In order to use the same style we choose, you can use this illustration [Icons8](https://icons8.com/illustrations/technologies/style--business-3d) so we can recreate a similar style

**Comment by saliougaye** [comment]
Closed with d82b0c3999ddbfa12d8709020644a02246984159
